import { readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const publicDir = path.join(root, "public");
const outputFile = path.join(root, "lib", "generatedAssets.ts");

const framePattern = /^frame-(\d+)\.png$/i;

async function readFrames(relativeDir) {
  const absoluteDir = path.join(publicDir, relativeDir);

  try {
    const files = await readdir(absoluteDir);
    return files
      .map((file) => {
        const match = file.match(framePattern);
        return match ? { file, index: Number(match[1]) } : null;
      })
      .filter(Boolean)
      .sort((a, b) => a.index - b.index)
      .map(({ file }) => `/${relativeDir.replaceAll("\\", "/")}/${file}`);
  } catch {
    return [];
  }
}

async function readSpriteFolders(relativeDir) {
  const absoluteDir = path.join(publicDir, relativeDir);

  try {
    const entries = await readdir(absoluteDir);
    const folders = [];

    for (const entry of entries) {
      const entryPath = path.join(absoluteDir, entry);
      if ((await stat(entryPath)).isDirectory()) folders.push(entry);
    }

    folders.sort((a, b) => a.localeCompare(b));
    return folders;
  } catch {
    return [];
  }
}

async function buildManifest(relativeDir) {
  const folders = await readSpriteFolders(relativeDir);
  const manifest = {};

  for (const folder of folders) {
    manifest[folder] = await readFrames(path.join(relativeDir, folder));
  }

  return manifest;
}

async function buildPetVariants() {
  const folders = await readSpriteFolders("assets");
  const petFolders = folders.filter((folder) => /^pet\d*$/i.test(folder));
  petFolders.sort((a, b) => {
    if (a.toLowerCase() === "pet") return -1;
    if (b.toLowerCase() === "pet") return 1;
    return a.localeCompare(b, undefined, { numeric: true });
  });

  const variants = {};
  for (const folder of petFolders) {
    variants[folder] = await buildManifest(path.join("assets", folder));
  }

  return variants;
}

const backgrounds = await buildManifest("assets/backgrounds");
const petVariants = await buildPetVariants();
const pet = petVariants.pet ?? await buildManifest("assets/pet");

const file = `// This file is generated by scripts/generate-assets.mjs. Do not edit manually.\n\nexport const GENERATED_BACKGROUNDS = ${JSON.stringify(backgrounds, null, 2)} as const;\n\nexport const GENERATED_PET_FRAMES = ${JSON.stringify(pet, null, 2)} as const;\n\nexport const GENERATED_PET_VARIANTS = ${JSON.stringify(petVariants, null, 2)} as const;\n`;

await writeFile(outputFile, file);
