// This file is generated by scripts/generate-assets.mjs. Do not edit manually.

export const GENERATED_BACKGROUNDS = {
  "Bad": [
    "/assets/backgrounds/Bad/frame-01.png"
  ],
  "Küche": [
    "/assets/backgrounds/Küche/frame-01.png"
  ],
  "Schlafzimmer": [
    "/assets/backgrounds/Schlafzimmer/frame-01.png"
  ],
  "UI": [],
  "Wiese": [
    "/assets/backgrounds/Wiese/frame-01.png"
  ],
  "Wohnzimmer": [
    "/assets/backgrounds/Wohnzimmer/frame-01.png"
  ]
} as const;

export const GENERATED_PET_FRAMES = {
  "laufen": [
    "/assets/pet/laufen/frame-01.png",
    "/assets/pet/laufen/frame-02.png",
    "/assets/pet/laufen/frame-03.png",
    "/assets/pet/laufen/frame-04.png",
    "/assets/pet/laufen/frame-05.png"
  ],
  "sitzen": [
    "/assets/pet/sitzen/frame-01.png",
    "/assets/pet/sitzen/frame-02.png",
    "/assets/pet/sitzen/frame-03.png",
    "/assets/pet/sitzen/frame-04.png",
    "/assets/pet/sitzen/frame-05.png",
    "/assets/pet/sitzen/frame-06.png",
    "/assets/pet/sitzen/frame-07.png",
    "/assets/pet/sitzen/frame-08.png",
    "/assets/pet/sitzen/frame-09.png",
    "/assets/pet/sitzen/frame-10.png",
    "/assets/pet/sitzen/frame-11.png"
  ],
  "sleep": [
    "/assets/pet/sleep/frame-01.png"
  ],
  "springen": [
    "/assets/pet/springen/frame-01.png",
    "/assets/pet/springen/frame-02.png",
    "/assets/pet/springen/frame-03.png",
    "/assets/pet/springen/frame-04.png",
    "/assets/pet/springen/frame-05.png"
  ],
  "stehen": [
    "/assets/pet/stehen/frame-01.png",
    "/assets/pet/stehen/frame-02.png",
    "/assets/pet/stehen/frame-03.png",
    "/assets/pet/stehen/frame-04.png",
    "/assets/pet/stehen/frame-05.png",
    "/assets/pet/stehen/frame-06.png",
    "/assets/pet/stehen/frame-07.png"
  ]
} as const;

export const GENERATED_PET_VARIANTS = {
  "pet": {
    "laufen": [
      "/assets/pet/laufen/frame-01.png",
      "/assets/pet/laufen/frame-02.png",
      "/assets/pet/laufen/frame-03.png",
      "/assets/pet/laufen/frame-04.png",
      "/assets/pet/laufen/frame-05.png"
    ],
    "sitzen": [
      "/assets/pet/sitzen/frame-01.png",
      "/assets/pet/sitzen/frame-02.png",
      "/assets/pet/sitzen/frame-03.png",
      "/assets/pet/sitzen/frame-04.png",
      "/assets/pet/sitzen/frame-05.png",
      "/assets/pet/sitzen/frame-06.png",
      "/assets/pet/sitzen/frame-07.png",
      "/assets/pet/sitzen/frame-08.png",
      "/assets/pet/sitzen/frame-09.png",
      "/assets/pet/sitzen/frame-10.png",
      "/assets/pet/sitzen/frame-11.png"
    ],
    "sleep": [
      "/assets/pet/sleep/frame-01.png"
    ],
    "springen": [
      "/assets/pet/springen/frame-01.png",
      "/assets/pet/springen/frame-02.png",
      "/assets/pet/springen/frame-03.png",
      "/assets/pet/springen/frame-04.png",
      "/assets/pet/springen/frame-05.png"
    ],
    "stehen": [
      "/assets/pet/stehen/frame-01.png",
      "/assets/pet/stehen/frame-02.png",
      "/assets/pet/stehen/frame-03.png",
      "/assets/pet/stehen/frame-04.png",
      "/assets/pet/stehen/frame-05.png",
      "/assets/pet/stehen/frame-06.png",
      "/assets/pet/stehen/frame-07.png"
    ]
  },
  "pet2": {
    "laufen": [
      "/assets/pet2/laufen/frame-01.png",
      "/assets/pet2/laufen/frame-02.png",
      "/assets/pet2/laufen/frame-03.png",
      "/assets/pet2/laufen/frame-04.png",
      "/assets/pet2/laufen/frame-05.png",
      "/assets/pet2/laufen/frame-06.png",
      "/assets/pet2/laufen/frame-07.png",
      "/assets/pet2/laufen/frame-08.png",
      "/assets/pet2/laufen/frame-09.png"
    ],
    "sitzen": [
      "/assets/pet2/sitzen/frame-01.png",
      "/assets/pet2/sitzen/frame-02.png",
      "/assets/pet2/sitzen/frame-03.png",
      "/assets/pet2/sitzen/frame-04.png",
      "/assets/pet2/sitzen/frame-05.png",
      "/assets/pet2/sitzen/frame-06.png",
      "/assets/pet2/sitzen/frame-07.png",
      "/assets/pet2/sitzen/frame-08.png",
      "/assets/pet2/sitzen/frame-09.png",
      "/assets/pet2/sitzen/frame-10.png"
    ],
    "sleep": [
      "/assets/pet2/sleep/frame-01.png",
      "/assets/pet2/sleep/frame-02.png"
    ],
    "springen": [
      "/assets/pet2/springen/frame-01.png",
      "/assets/pet2/springen/frame-02.png",
      "/assets/pet2/springen/frame-03.png",
      "/assets/pet2/springen/frame-04.png",
      "/assets/pet2/springen/frame-05.png",
      "/assets/pet2/springen/frame-06.png",
      "/assets/pet2/springen/frame-07.png",
      "/assets/pet2/springen/frame-08.png",
      "/assets/pet2/springen/frame-09.png",
      "/assets/pet2/springen/frame-10.png"
    ],
    "stehen": [
      "/assets/pet2/stehen/frame-01.png",
      "/assets/pet2/stehen/frame-02.png",
      "/assets/pet2/stehen/frame-03.png",
      "/assets/pet2/stehen/frame-04.png",
      "/assets/pet2/stehen/frame-05.png",
      "/assets/pet2/stehen/frame-06.png",
      "/assets/pet2/stehen/frame-07.png",
      "/assets/pet2/stehen/frame-08.png",
      "/assets/pet2/stehen/frame-09.png",
      "/assets/pet2/stehen/frame-10.png"
    ]
  }
} as const;
